version: '3.8'

services:
  app:
    build: .
    container_name: estoque_php_app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: estoque_user
      DB_PASSWORD: estoque_pass
      DB_NAME: estoque

  db:
    image: mysql:5.7
    container_name: estoque_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: estoque
      MYSQL_USER: estoque_user
      MYSQL_PASSWORD: estoque_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: estoque_phpmyadmin
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
      PMA_ABSOLUTE_URI: http://localhost:8081/
    ports:
      - "8081:80"

volumes:
  mysql_data:
